timeout: 0
interface_resolution: 1280x960x32

/SzpontOS (x86_64)
    protocol: limine
    resolution: 1280x960x32
    kernel_path: boot():/boot/szpontos-kernel
    module_path: boot():/boot/initramfs.tar
