# SzpontOS /etc/nsswitch.conf (Name Service Switch Configuration)
# (C) Copyright by Szpont Industries. All rights reserved.

hosts: files dns
passwd: files
group: files
services: files
protocols: files
