# SzpontOS /etc/resolv.conf (FreeBSD-compatible Resolver Configuration)
# (C) Copyright by Szpont Industries. All rights reserved.

nameserver 10.0.2.3
nameserver 1.1.1.1
nameserver 8.8.8.8
timeout 2
attempts 2
