#!/bin/bash
filtered_args=()
has_shared=0

for arg in "$@"; do
    if [ "$arg" = "-pthread" ]; then
        filtered_args+=("-D_REENTRANT")
    elif [ "$arg" = "-shared" ]; then
        has_shared=1
        filtered_args+=("$arg")
    else
        filtered_args+=("$arg")
    fi
done

if [ "$has_shared" -eq 1 ]; then
    exec x86_64-elf-g++ "${filtered_args[@]}" -nostartfiles /Users/rafal/Projects/SzpontOS/build/sysroot/usr/lib/dso_handle.o -Wl,-shared -Wl,-z,undefs
else
    exec x86_64-elf-g++ "${filtered_args[@]}"
fi
