#!/bin/bash
has_shared=0
for arg in "$@"; do
    if [ "$arg" = "-shared" ]; then
        has_shared=1
        break
    fi
done

if [ "$has_shared" -eq 1 ]; then
    exec x86_64-elf-gcc "$@" -nostartfiles -Wl,-shared -Wl,-z,undefs
else
    exec x86_64-elf-gcc "$@"
fi
